---
output: 
  html_document:
    includes:
      in_header: test1.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)

set.seed(12)
library(ggplot2)

x1 <- rnorm(50, 10, 2)

x2 <- scale(matrix(rnorm(50), ncol=1))
x12 <- cbind(scale(x1),x2)

c1 <- var(x12)
chol1 <- solve(chol(c1))
newx <-  x12 %*% chol1

newc <- matrix(c(1,-0.52, -0.52, 1), ncol=2)
chol2 <- chol(newc)
finalx <- newx %*% chol2 * sd(x1) + mean(x1)

finalx[,2] <- (2*finalx[,2]-5)

giraffe_data <- finalx
colnames(giraffe_data) <- c("Heights", "Celery_Eaten")

giraffe_data <- as.data.frame(giraffe_data)

```


```{r 05-make-scatter, exercise=TRUE}
# Create a scatterplot using the instructions above

```

```{r 05-make-scatter-solution}
p <-  ggplot(data= giraffe_data, aes(x= Heights, y=Celery_Eaten)) +
  geom_point() + 
  geom_vline(xintercept = mean(giraffe_data$Heights)) + 
  geom_hline(yintercept = mean(giraffe_data$Celery_Eaten))

p
```

<div data-iframe-height></div>
